In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("netflix_titles.csv")

In [30]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

In [32]:
df.shape

(6234, 12)

In [33]:
df.isnull().sum()

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [37]:
df['director'] = df['director'].fillna("Unknown")

In [38]:
df['director'] = df['director'].fillna("Unknown")
df['cast'] = df['cast'].fillna("Not Available")
df['country'] = df['country'].fillna("Unknown")

In [39]:
df = df.dropna(subset=['date_added'])

In [40]:
df = df.drop_duplicates()

In [41]:
df = df.reset_index(drop=True)

In [42]:
df.duplicated().sum()

np.int64(0)

In [44]:
df['date_added'] = df['date_added'].str.strip()

In [45]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [46]:
df[df['date_added'].isna()]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6223 entries, 0 to 6222
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6223 non-null   int64
 1   type          6223 non-null   object
 2   title         6223 non-null   object
 3   director      6223 non-null   object
 4   cast          6223 non-null   object
 5   country       6223 non-null   object
 6   date_added    6223 non-null   datetime64[ns]
 7   release_year  6223 non-null   int64
 8   rating        6214 non-null   object
 9   duration      6223 non-null   object
 10  listed_in     6223 non-null   object
 11  description   6223 non-null   object
dtypes: datetime64[ns](1), int64(2), object(9)
memory usage: 583.5+ KB

In [48]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [49]:
df['duration_int'] = df['duration'].str.extract('(\d+)')
df['duration_int'] = df['duration_int'].astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1326/989630569.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['duration_int'] = df['duration'].str.extract('(\d+)')

In [50]:
df['type'] = df['type'].str.strip()
df['country'] = df['country'].str.strip()
df['rating'] = df['rating'].str.strip()

In [51]:
df['country'] = df['country'].str.split(',').str[0]

In [52]:
df.reset_index(drop=True, inplace=True)

In [54]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          9
duration        0
listed_in       0
description     0
year_added      0
month_added     0
duration_int    0
dtype: int64

In [55]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,duration_int
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...",United States,2019-09-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,2019,9,90
1,80117401,Movie,Jandino: Whatever it Takes,Unknown,Jandino Asporaat,United Kingdom,2016-09-09,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2016,9,94
2,70234439,TV Show,Transformers Prime,Unknown,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",2018,9,1
3,80058654,TV Show,Transformers: Robots in Disguise,Unknown,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,2018,9,1
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09-08,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,2017,9,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6218,80162994,TV Show,Talking Tom and Friends,Unknown,"Colin Hanks, Tom Kenny, James Adomian, Lisa Sc...",Cyprus,2019-04-10,2017,TV-G,2 Seasons,"Kids' TV, TV Comedies",Full of funny one-liners and always ready for ...,2019,4,2
6219,80186475,TV Show,Pokémon the Series,Unknown,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,2019-04-01,2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV",Ash and his Pikachu travel to the Alola region...,2019,4,2
6220,70272742,TV Show,Justin Time,Unknown,"Gage Munroe, Scott McCord, Jenna Warren",Canada,2016-04-01,2012,TV-Y,2 Seasons,Kids' TV,"In Justin's dreams, he and his imaginary frien...",2016,4,2
6221,80067942,TV Show,Terrace House: Boys & Girls in the City,Unknown,"You, Reina Triendl, Ryota Yamasato, Yoshimi To...",Japan,2016-04-01,2016,TV-14,2 Seasons,"International TV Shows, Reality TV",A new set of six men and women start their liv...,2016,4,2
6222,70136122,TV Show,Weeds,Unknown,"Mary-Louise Parker, Hunter Parrish, Alexander ...",United States,2014-04-01,2012,TV-MA,8 Seasons,"TV Comedies, TV Dramas",A suburban mother starts selling marijuana to ...,2014,4,8